### ISSUE TITLE
Define a singleton for the orthotope's Shape

### ISSUE THREAD

**Issue by Mikolaj** [Mikolaj/horde-ad#104]
That would require depending on packages `singletons-base` and `singletons`. The idea is to be able do

```hs
import           Data.Singletons (sing)
import           Data.Singletons.Decide (Decision (Proved), (%~))
...
... Shape sh2, Shape sh1 ...
---
     SToR @_ @_ @sh2 (RToS @_ @_ @sh1 d) ->
      case sing @sh1 %~ sing @sh2 of
        Proved{} -> evalR s c d
        _ -> error "panic!"
```

and I suspect we'd need something like

```hs
instance Shape sh => SingI sh where
  sing = shapeP
```

to make it possible, where `shapeP` is defined in 

https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/src/Data.Array.Internal.Shape.html#Shape

but `shapeP` is not enough and I can't do better. Either we'd need to patch `orthotope` or use the `[Int]` result of `shapeP` somehow (convert it into the singleton type for [Nat]? what is this type?), but I'm afraid that's too crude and it's going to impose a runtime cost even if the types can be determined statically --- but perhaps the cost is paid regardless? In any case, is there an obvious simple way to do this? The end of the following page suggests there should be: https://hackage.haskell.org/package/typelits-witnesses-0.3.0.2

**Comment by tomsmeding** [comment]
What exactly would be the reason for wanting a singleton for orthotope's shapes? Is it that having a `Proxy (s :: [Nat])` is not enough when wanting to do some runtime-determined arithmetic on the shape?

Would it not be sufficient to just define the appropriate singleton-like GADT manually? `singletons` (disclaimer: I haven't ever actually used `singletons`) is, as far as I know, "simply" a bunch of automation for generating such data types with conversion functions. But they're easily manually written, if a tad tedious if you need to do it for a lot of types. (Perhaps the library also offers some functions for the interaction between multiple different singletons, somehow.)

> the singleton type for [Nat]? what is this type?

This?

```hs
import GHC.TypeLits (Nat, KnownNat)

data SNat (n :: Nat) where
  SNat :: KnownNat n => SNat n

data SShape (s :: [Nat]) where
  SShapeNil :: SShape []
  SShapeCons :: SNat n -> SShape s -> SShape (n ': s)
```

The recipe for defining a singleton type for an ADT `T` is to first make sure you have `T` itself defined, and then to make a GADT (with one type parameter of kind `T`) that mirrors `T`'s structure, replacing the fields with singletons for the fields and setting the type tag to the corresponding `T` constructor with the appropriate arguments. `SShape` above is that for `[Nat]`. `SNat` is special because `Nat` is special.

**Comment by Mikolaj** [comment]
The use case is the following: I have `sh1` and `sh2` about which I only know `OS.Shape sh` and `OS.Shape sh2`. Now I need to compare the types and, if they are equal, use that type equality for typing some other code. That's what the example above was about. I don't mind using proxies for that. I just through `sing` would be easier, because the singletons package already defines type equality (`%~`, similar to `sameNat`) for Nat and for lists. However, it's not only the question of composing the two, because I'd need to get such composed singleton from merely the `Shape` constraints.

Let me copy an example with `sameNat` together with that with `%~` to make it clear what I mean:

```hs
... KnownNat n1, KnownNat n2 ...
...
        DToS @n2 (SToD @_ @_ @n1 d) ->
          case sameNat (Proxy @n1) (Proxy @n2) of
            Just Refl -> evalS s c d
            _ -> error "buildFinMaps: different shapes in DToS(SToD)"
```

vs

```hs
... Shape sh2, Shape sh1 ...
...
     SToR @_ @_ @sh2 (RToS @_ @_ @sh1 d) ->
      case sing @sh1 %~ sing @sh2 of
        Proved{} -> evalR s c d
        _ -> error "panic!"
```

**Comment by tomsmeding** [comment]
Oh wow you have Dynamic <-> Ranked <-> Shaped conversions _in `Delta`_ now? I had no idea.

This snippet:
```hs
        DToR @_ @_ @n2 (RToD @_ @_ @n1 d) ->
          case sameNat (Proxy @n1) (Proxy @n2) of
            Just Refl -> evalR s c d
            _ -> error "buildFinMaps: different ranks in DToR(RToD)"
```
works because the actual values to compare come from the `KnownNat` dictionaries. (Note that you copied some code with `S`, whereas I believe you meant to copy the `R` block right above.) In particular, `KnownNat n1` comes from the `RToD` constructor, and `KnownNat n2` comes from the enclosing function because the rank of the outermost expression is known.

Now in your shaped snippet:
```hs
        SToR @_ @_ @sh2 (RToS @_ @_ @sh1 d) ->
          -- TODO: compare sh, not n:
          case sameNat (Proxy @(OS.Rank sh1)) (Proxy @(OS.Rank sh2)) of
            Just Refl -> evalR s c d
            _ -> error "buildFinMaps: different shapes in SToR(RToS)"
```
we have no `Shape` dictionaries at all. The current code typechecks because we know `KnownNat (OS.Rank sh2)` from the enclosing function, as before, combined with the fact that GHC actually already knows that `sh1 ~ sh2`; the following typechecks:
```hs
        SToR @_ @_ @sh2 (RToS @_ @_ @sh1 d) ->
          let r = Refl :: sh1 :~: sh2 in
          -- TODO: compare sh, not n:
-- ...
```
which makes sense when looking at the types of `SToR` and `RToS`. So your `case` here is actually unnecessary: the following also typechecks:
```hs
        SToR @_ @_ @sh2 (RToS @_ @_ @sh1 d) ->
          evalR s c d
```
but this only works because, contrary to the earlier `DToR (RToD d)` case, we're not downcasting (from R to D) in the middle, we're _upcasting_ (from R to S) in the middle. No information is lost.

Now over in `evalS`:
```hs
        DToS (SToD @_ @_ @sh1 d) ->
          -- TODO: compare sh, not n:
          case sameNat (Proxy @(OS.Rank sh1)) (Proxy @(OS.Rank sh)) of
            Just Refl -> _evalS s c d
            _ -> error "buildFinMaps: different shapes in DToS(SToD)"
```
information _is_ of course lost in the middle. What we are to do is to check whether `sh` and `sh1` are equal, given `(OS.Shape sh1, KnownNat (OS.Rank sh1))` (from `SToD`), and `KnownNat (OS.Rank sh)` from `evalS`'s type signature. That ain't gonna work, `evalS` will also need a `OS.Shape sh`. Let's assume that's there.

But then still, as you found, it won't work because `shapeP` doesn't return a singleton. However, assuming that all `OS.Shape` instances are sound, we can hack our own evidence in:
```hs
sameShape :: forall s1 s2. (OS.Shape s1, OS.Shape s2) => Maybe (s1 :~: s2)
sameShape
  | shapeP (Proxy @s1) == shapeP (Proxy @s2) = Just (unsafeCoerce (Refl :: s1 :~: s2))
  | otherwise = Nothing
```
Alternatively, possibly slightly less performantly (but I don't think that matters much in this part of the code), we can sneakily note that:
```hs
class Typeable s => Shape (s :: [Nat]) where
```
hence:
```hs
import Type.Reflection (typeRep, eqTypeRep, (:~~:)(HRefl))
sameShape :: forall s1 s2. (OS.Shape s1, OS.Shape s2) => Maybe (s1 :~: s2)
sameShape = case eqTypeRep (typeRep @s1) (typeRep @s2) of
              Just HRefl -> Just Refl
              Nothing -> Nothing
```
which is safe.

Does that help?

**Comment by Mikolaj** [comment]
> Oh wow you have Dynamic <-> Ranked <-> Shaped conversions _in `Delta`_ now? I had no idea.

Yeah, I have them everywhere, though it's WIP. I need them mainly to see if the immense simplification induced by your sneaky refactoring idea doesn't go too far (barely any code is left now and I've even managed to remove all Tannen and Compose at the cost of a few Clowns). And, yes, they are needed in `Delta`, though most of the time (in currently tests, always, because ATM the user can't request them, so only adaptors add them) they are optimized away before being stored on the tape.

> (Note that you copied some code with `S`, whereas I believe you meant to copy the `R` block right above.) 

Hah, I admit, I copied a random snippet, tweaked the names and hoped nobody would notice. ;D

> In particular, `KnownNat n1` comes from the `RToD` constructor, and `KnownNat n2` comes from the enclosing function because the rank of the outermost expression is known.

Correct.

> Now in your shaped snippet:
> 
> ```haskell
>         SToR @_ @_ @sh2 (RToS @_ @_ @sh1 d) ->
>           -- TODO: compare sh, not n:
>           case sameNat (Proxy @(OS.Rank sh1)) (Proxy @(OS.Rank sh2)) of
>             Just Refl -> evalR s c d
>             _ -> error "buildFinMaps: different shapes in SToR(RToS)"
> ```
> 
> we have no `Shape` dictionaries at all. The current code typechecks because we know `KnownNat (OS.Rank sh2)` from the enclosing function, as before, combined with the fact that GHC actually already knows that `sh1 ~ sh2`

Wow, you are right. And by transitivity

    let r = Refl :: (OS.Rank sh1) :~: n in

so I don't have to check anything, just as you said.

> Alternatively, possibly slightly less performantly (but I don't think that matters much in this part of the code)

I have no clue about performance of such things (e.g., I usually expect compile-time execution, not run-time), so let me pick the safer one.

> Does that help?

Completely.
